language: erlang

notifications:
  disabled: true
sudo: required

script:
  - rebar get-deps
  - rebar compile
  - rebar xref
  - rebar eunit
  - |
     if [ $TRAVIS_OTP_RELEASE == 17.4 ]
        then
          make dialyzer
        else
         true
     fi


otp_release:
   - 17.4
   - 17.3
   - 17.1
   - 17.0
   - R16B03-1
   - R16B02
